name: Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      lambda_function_name:
        description: 'Name of the Lambda function'
        required: true
      docker_image_selection:
        description: 'Select the Docker image to use'
        required: true
        type: choice
        options:
          - lambda-docker-google-drive
          - lambda-docker-s3-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        env:
          TF_VAR_docker_image_selection: ${{ github.event.inputs.docker_image_selection }}
          TF_VAR_lambda_function_name: ${{ github.event.inputs.lambda_function_name }}
          TF_VAR_lambda_suffix: ${{ github.run_id }}  